const users = [
  {
    street: 'Jimmie Motorway',
    country: 'Greece',
    city: 'Holdenport',
    name: 'Ms. Lola Kuvalis',
    age: 45,
    buildingNum: '654',
    firstName: 'Timmothy',
    lastName: 'Dibbert',
    namePrefix: 'Ms.',
    nameSuffix: 'IV',
    phonenum: '283-867-0057'
  },
  {
    street: 'Johan Corners',
    country: 'Uganda',
    city: 'East Raquelchester',
    name: 'Dr. Esther Mills',
    age: 31,
    buildingNum: '7848',
    firstName: 'Raymundo',
    lastName: 'Schaefer',
    namePrefix: 'Dr.',
    nameSuffix: 'DVM',
    phonenum: '121-297-1676'
  },
  {
    street: 'Abshire Station',
    country: 'Holy See (Vatican City State)',
    city: 'North Lamont',
    name: 'Ms. Karson Johns',
    age: 53,
    buildingNum: '792',
    firstName: 'Bridie',
    lastName: 'Lindgren',
    namePrefix: 'Miss',
    nameSuffix: 'DDS',
    phonenum: '411-026-9863'
  },
  {
    street: 'Josefina Roads',
    country: 'South Africa',
    city: 'New Mike',
    name: 'Mrs. Ashlee Macejkovic',
    age: 71,
    buildingNum: '804',
    firstName: 'Jimmie',
    lastName: 'Emmerich',
    namePrefix: 'Miss',
    nameSuffix: 'DDS',
    phonenum: '500-551-0166'
  },
  {
    street: 'Wyman Skyway',
    country: 'Niger',
    city: 'Nicholaschester',
    name: 'Mrs. Alisa Hammes',
    age: 56,
    buildingNum: '095',
    firstName: 'Everett',
    lastName: 'Bosco',
    namePrefix: 'Miss',
    nameSuffix: 'IV',
    phonenum: '366-681-7515'
  },
  {
    street: 'Russel Viaduct',
    country: 'United States of America',
    city: 'West Niamouth',
    name: 'Dr. Adelbert Tillman',
    age: 42,
    buildingNum: '28',
    firstName: 'Landen',
    lastName: 'Koss',
    namePrefix: 'Mrs.',
    nameSuffix: 'I',
    phonenum: '720-964-5904'
  },
  {
    street: 'Danny Throughway',
    country: 'Russian Federation',
    city: 'Reannabury',
    name: 'Miss Maxime Schmitt',
    age: 47,
    buildingNum: '88',
    firstName: 'Maggie',
    lastName: 'Padberg',
    namePrefix: 'Ms.',
    nameSuffix: 'II',
    phonenum: '594-614-3148'
  },
  {
    street: 'Porter Gateway',
    country: 'Haiti',
    city: 'Maudiemouth',
    name: 'Ms. Murl Labadie',
    age: 49,
    buildingNum: '0991',
    firstName: 'Abdullah',
    lastName: 'Schulist',
    namePrefix: 'Mrs.',
    nameSuffix: 'III',
    phonenum: '177-129-0397'
  },
  {
    street: 'Litzy Square',
    country: 'Chile',
    city: 'Lake Jerad',
    name: 'Ms. Edison Beahan',
    age: 32,
    buildingNum: '372',
    firstName: 'Kevon',
    lastName: 'Bernhard',
    namePrefix: 'Ms.',
    nameSuffix: 'II',
    phonenum: '923-585-0681'
  },
  {
    street: 'Terrance Heights',
    country: 'Saudi Arabia',
    city: 'Langland',
    name: 'Miss Josefa Botsford',
    age: 19,
    buildingNum: '265',
    firstName: 'Tyson',
    lastName: 'Bahringer',
    namePrefix: 'Mrs.',
    nameSuffix: 'Sr.',
    phonenum: '378-317-7344'
  },
  {
    street: 'Amari Curve',
    country: 'Falkland Islands (Malvinas)',
    city: 'Johnstonport',
    name: 'Miss Betty Rogahn',
    age: 29,
    buildingNum: '932',
    firstName: 'Robyn',
    lastName: 'Dietrich',
    namePrefix: 'Miss',
    nameSuffix: 'Sr.',
    phonenum: '693-216-8135'
  },
  {
    street: 'Neal Valley',
    country: 'Lesotho',
    city: 'East Ronaldo',
    name: 'Ms. Laury Kris',
    age: 24,
    buildingNum: '841',
    firstName: 'Bobbie',
    lastName: 'Ziemann',
    namePrefix: 'Mrs.',
    nameSuffix: 'DDS',
    phonenum: '603-798-7402'
  },
  {
    street: 'Larue Orchard',
    country: 'Vietnam',
    city: 'North Quinn',
    name: 'Miss Kiana Crona',
    age: 33,
    buildingNum: '881',
    firstName: 'Orpha',
    lastName: 'Kunde',
    namePrefix: 'Mrs.',
    nameSuffix: 'DDS',
    phonenum: '329-161-7779'
  },
  {
    street: 'Quitzon Locks',
    country: 'Sierra Leone',
    city: 'New Diana',
    name: 'Ms. Margarett Hoeger',
    age: 57,
    buildingNum: '5918',
    firstName: 'Linwood',
    lastName: 'Konopelski',
    namePrefix: 'Ms.',
    nameSuffix: 'PhD',
    phonenum: '927-818-5979'
  },
  {
    street: 'Turcotte Terrace',
    country: 'Czech Republic',
    city: 'West Aubree',
    name: 'Ms. Manuela Rosenbaum',
    age: 64,
    buildingNum: '138',
    firstName: 'Brody',
    lastName: 'Marquardt',
    namePrefix: 'Miss',
    nameSuffix: 'II',
    phonenum: '468-625-4025'
  },
  {
    street: 'Prudence Street',
    country: 'Faroe Islands',
    city: 'Mayeside',
    name: 'Mr. Vergie Beer',
    age: 64,
    buildingNum: '2834',
    firstName: 'Jonas',
    lastName: 'Halvorson',
    namePrefix: 'Ms.',
    nameSuffix: 'III',
    phonenum: '566-961-2069'
  },
  {
    street: 'Farrell Plain',
    country: 'Papua New Guinea',
    city: 'Lake Maddison',
    name: 'Ms. Manuel Ward',
    age: 34,
    buildingNum: '647',
    firstName: 'Stephen',
    lastName: 'Wilderman',
    namePrefix: 'Ms.',
    nameSuffix: 'DVM',
    phonenum: '325-664-2132'
  },
  {
    street: 'Barton Knolls',
    country: 'Seychelles',
    city: 'New Deltaview',
    name: 'Ms. Eleanora Carter',
    age: 59,
    buildingNum: '7165',
    firstName: 'Kristin',
    lastName: 'Johnson',
    namePrefix: 'Ms.',
    nameSuffix: 'II',
    phonenum: '156-583-8105'
  },
  {
    street: 'Elvie Ferry',
    country: 'Estonia',
    city: 'South Elian',
    name: 'Ms. Kaleb McClure',
    age: 77,
    buildingNum: '39',
    firstName: 'Jazmyn',
    lastName: 'Dach',
    namePrefix: 'Mrs.',
    nameSuffix: 'PhD',
    phonenum: '349-507-4285'
  },
  {
    street: 'Cummerata Shore',
    country: 'Brunei Darussalam',
    city: 'Cadenside',
    name: 'Mrs. Beatrice Gibson',
    age: 45,
    buildingNum: '484',
    firstName: 'Marguerite',
    lastName: 'Tromp',
    namePrefix: 'Miss',
    nameSuffix: 'IV',
    phonenum: '830-322-2358'
  },
  {
    street: 'Turcotte Burgs',
    country: 'Tanzania',
    city: 'North Bernhardberg',
    name: 'Ms. Flo Roberts',
    age: 74,
    buildingNum: '599',
    firstName: 'Filomena',
    lastName: 'Koepp',
    namePrefix: 'Ms.',
    nameSuffix: 'PhD',
    phonenum: '037-366-7207'
  },
  {
    street: 'Lueilwitz Alley',
    country: 'Congo',
    city: 'Port Kailey',
    name: 'Ms. Veronica Macejkovic',
    age: 54,
    buildingNum: '5838',
    firstName: 'Demario',
    lastName: 'Mayert',
    namePrefix: 'Miss',
    nameSuffix: 'Sr.',
    phonenum: '776-442-5295'
  },
  {
    street: 'Altenwerth Lane',
    country: 'Holy See (Vatican City State)',
    city: 'East Savannah',
    name: 'Mr. Will Hills',
    age: 43,
    buildingNum: '483',
    firstName: 'Garrett',
    lastName: 'Wyman',
    namePrefix: 'Mr.',
    nameSuffix: 'III',
    phonenum: '262-674-4398'
  },
  {
    street: 'Orn Land',
    country: 'Nigeria',
    city: 'Robbside',
    name: 'Dr. Eva Von',
    age: 50,
    buildingNum: '7924',
    firstName: 'Vilma',
    lastName: 'Trantow',
    namePrefix: 'Ms.',
    nameSuffix: 'IV',
    phonenum: '821-808-4565'
  },
  {
    street: 'Alba Stravenue',
    country: 'Iraq',
    city: 'South Savanah',
    name: 'Mr. Deonte Bosco',
    age: 61,
    buildingNum: '72',
    firstName: 'Isabell',
    lastName: 'Herzog',
    namePrefix: 'Miss',
    nameSuffix: 'II',
    phonenum: '776-544-6607'
  },
  {
    street: 'Renee Underpass',
    country: 'Somalia',
    city: 'Mantefurt',
    name: 'Miss Annabell Ondricka',
    age: 25,
    buildingNum: '009',
    firstName: 'Flossie',
    lastName: 'Quigley',
    namePrefix: 'Ms.',
    nameSuffix: 'Sr.',
    phonenum: '994-031-2750'
  },
  {
    street: 'Kathryne Common',
    country: 'Lithuania',
    city: 'South Destini',
    name: 'Ms. Nola Deckow',
    age: 53,
    buildingNum: '9595',
    firstName: 'Mateo',
    lastName: 'Homenick',
    namePrefix: 'Mr.',
    nameSuffix: 'MD',
    phonenum: '268-567-5736'
  },
  {
    street: 'Nikolaus Shoals',
    country: 'Jordan',
    city: 'Lake Olga',
    name: 'Miss Addie Zboncak',
    age: 61,
    buildingNum: '493',
    firstName: 'Ettie',
    lastName: 'Wehner',
    namePrefix: 'Mr.',
    nameSuffix: 'IV',
    phonenum: '564-583-6272'
  },
  {
    street: 'Kessler Ports',
    country: 'Tonga',
    city: 'Maiyamouth',
    name: 'Miss Sister Quitzon',
    age: 65,
    buildingNum: '1275',
    firstName: 'Justus',
    lastName: 'Rau',
    namePrefix: 'Dr.',
    nameSuffix: 'PhD',
    phonenum: '764-352-0427'
  },
  {
    street: 'Farrell Ports',
    country: 'Bhutan',
    city: 'Valentinafurt',
    name: 'Miss Nathen Bergstrom',
    age: 62,
    buildingNum: '69',
    firstName: 'Jess',
    lastName: 'Kozey',
    namePrefix: 'Mrs.',
    nameSuffix: 'PhD',
    phonenum: '027-552-8016'
  },
  {
    street: 'Franecki Skyway',
    country: 'Afghanistan',
    city: 'Arvillaland',
    name: 'Miss Grant Kuhn',
    age: 28,
    buildingNum: '341',
    firstName: 'Christ',
    lastName: 'Bergstrom',
    namePrefix: 'Miss',
    nameSuffix: 'I',
    phonenum: '312-306-9895'
  },
  {
    street: 'Walsh Crest',
    country: 'Malaysia',
    city: 'New Velvaside',
    name: 'Mrs. Carmel Carter',
    age: 49,
    buildingNum: '628',
    firstName: 'Ransom',
    lastName: 'Zieme',
    namePrefix: 'Mrs.',
    nameSuffix: 'PhD',
    phonenum: '072-413-1603'
  },
  {
    street: 'Mertz Inlet',
    country: 'Belarus',
    city: 'South Bettyeborough',
    name: 'Miss Clair Waelchi',
    age: 29,
    buildingNum: '691',
    firstName: 'Dwight',
    lastName: 'Bergnaum',
    namePrefix: 'Miss',
    nameSuffix: 'IV',
    phonenum: '063-783-9079'
  },
  {
    street: 'Rogelio Estate',
    country: 'Lithuania',
    city: 'Bechtelarfurt',
    name: 'Mrs. Jackie Schulist',
    age: 26,
    buildingNum: '7340',
    firstName: 'Felicia',
    lastName: 'Wehner',
    namePrefix: 'Mrs.',
    nameSuffix: 'PhD',
    phonenum: '625-196-8561'
  },
  {
    street: 'Giovanni Springs',
    country: 'Portugal',
    city: 'Hahnton',
    name: 'Mr. Danyka Huels',
    age: 49,
    buildingNum: '8489',
    firstName: 'Rod',
    lastName: 'Jacobson',
    namePrefix: 'Mr.',
    nameSuffix: 'MD',
    phonenum: '565-017-1858'
  },
  {
    street: 'Donato Meadows',
    country: 'Burkina Faso',
    city: 'Lake Delaney',
    name: 'Miss Alva Pacocha',
    age: 67,
    buildingNum: '19',
    firstName: 'Gustave',
    lastName: 'Blick',
    namePrefix: 'Miss',
    nameSuffix: 'Jr.',
    phonenum: '412-966-0079'
  },
  {
    street: 'Jaqueline Stravenue',
    country: 'Botswana',
    city: 'Aylastad',
    name: 'Miss Brianne Gusikowski',
    age: 60,
    buildingNum: '349',
    firstName: 'Caleb',
    lastName: 'Dickinson',
    namePrefix: 'Mrs.',
    nameSuffix: 'MD',
    phonenum: '973-645-4858'
  },
  {
    street: 'Maximus Burg',
    country: 'Myanmar',
    city: 'Leoraburgh',
    name: 'Mr. Alexandro Pollich',
    age: 28,
    buildingNum: '032',
    firstName: 'Alexzander',
    lastName: 'Oberbrunner',
    namePrefix: 'Dr.',
    nameSuffix: 'I',
    phonenum: '734-069-1463'
  },
  {
    street: 'Nolan Squares',
    country: 'Angola',
    city: 'New Kaci',
    name: 'Mrs. Teresa Collins',
    age: 38,
    buildingNum: '440',
    firstName: 'Raquel',
    lastName: 'Kuhic',
    namePrefix: 'Ms.',
    nameSuffix: 'PhD',
    phonenum: '540-335-4817'
  },
  {
    street: 'Jaskolski Crossroad',
    country: 'Barbados',
    city: 'New Eliseport',
    name: 'Mrs. Consuelo Langosh',
    age: 78,
    buildingNum: '192',
    firstName: 'Orlando',
    lastName: 'Langworth',
    namePrefix: 'Ms.',
    nameSuffix: 'PhD',
    phonenum: '011-210-6197'
  },
  {
    street: 'Elsie Harbors',
    country: 'Anguilla',
    city: 'North Tommie',
    name: 'Mrs. Terrell Witting',
    age: 27,
    buildingNum: '792',
    firstName: 'Albina',
    lastName: 'Thompson',
    namePrefix: 'Ms.',
    nameSuffix: 'Jr.',
    phonenum: '038-575-7200'
  },
  {
    street: 'Abner Mall',
    country: 'Cocos (Keeling) Islands',
    city: 'West Liana',
    name: 'Mrs. Fannie Parisian',
    age: 28,
    buildingNum: '4677',
    firstName: 'Petra',
    lastName: 'Flatley',
    namePrefix: 'Ms.',
    nameSuffix: 'IV',
    phonenum: '942-252-1057'
  },
  {
    street: 'Koelpin Ridge',
    country: 'Japan',
    city: 'Lake Orinfort',
    name: 'Mr. King Crona',
    age: 63,
    buildingNum: '564',
    firstName: 'Kaylin',
    lastName: 'Osinski',
    namePrefix: 'Miss',
    nameSuffix: 'III',
    phonenum: '375-785-6544'
  },
  {
    street: 'Marquis Camp',
    country: 'South Georgia and the South Sandwich Islands',
    city: 'South Mike',
    name: 'Ms. Jerry Graham',
    age: 80,
    buildingNum: '16',
    firstName: 'Fabiola',
    lastName: 'Anderson',
    namePrefix: 'Ms.',
    nameSuffix: 'Sr.',
    phonenum: '366-779-3416'
  },
  {
    street: 'Schamberger Garden',
    country: 'Falkland Islands (Malvinas)',
    city: 'Lake Margarette',
    name: 'Ms. Charity Mueller',
    age: 21,
    buildingNum: '203',
    firstName: 'Lea',
    lastName: 'Labadie',
    namePrefix: 'Mr.',
    nameSuffix: 'V',
    phonenum: '077-440-9701'
  },
  {
    street: 'Emard Passage',
    country: 'Gibraltar',
    city: 'Lake Eldora',
    name: 'Mrs. Davion Jakubowski',
    age: 41,
    buildingNum: '59',
    firstName: 'Jarrett',
    lastName: 'Pagac',
    namePrefix: 'Miss',
    nameSuffix: 'II',
    phonenum: '576-314-8440'
  },
  {
    street: 'Wilkinson Summit',
    country: 'Mali',
    city: 'New Sebastian',
    name: 'Ms. Carmela Frami',
    age: 51,
    buildingNum: '317',
    firstName: 'Vena',
    lastName: 'Crist',
    namePrefix: 'Mrs.',
    nameSuffix: 'V',
    phonenum: '552-244-0021'
  },
  {
    street: 'Marcelino Lake',
    country: 'Bouvet Island (Bouvetoya)',
    city: 'Borerville',
    name: 'Mrs. Bertram Sanford',
    age: 71,
    buildingNum: '14',
    firstName: 'Maudie',
    lastName: 'Cassin',
    namePrefix: 'Ms.',
    nameSuffix: 'Sr.',
    phonenum: '024-973-5168'
  },
  {
    street: 'Meaghan Mount',
    country: 'Aruba',
    city: 'West Yesseniabury',
    name: 'Mrs. Carroll Hudson',
    age: 24,
    buildingNum: '73',
    firstName: 'Abdiel',
    lastName: 'McClure',
    namePrefix: 'Dr.',
    nameSuffix: 'MD',
    phonenum: '426-105-2724'
  },
  {
    street: 'Blair Brooks',
    country: 'Hungary',
    city: 'Considinemouth',
    name: 'Ms. Alice Abernathy',
    age: 40,
    buildingNum: '40',
    firstName: 'Tiara',
    lastName: 'Conroy',
    namePrefix: 'Miss',
    nameSuffix: 'II',
    phonenum: '398-407-3330'
  },
  {
    street: 'Hahn Ridges',     
    country: 'Cuba',
    city: 'Heberborough',      
    name: 'Mrs. Eldon Price',  
    age: 27,
    buildingNum: '310',        
    firstName: 'Jamarcus',     
    lastName: 'Padberg',       
    namePrefix: 'Ms.',
    nameSuffix: 'IV',
    phonenum: '297-505-2948'   
  },
  {
    street: 'Nettie Haven',    
    country: 'Thailand',       
    city: 'West Abigale',      
    name: 'Mrs. Velda Bernier',
    age: 36,
    buildingNum: '298',        
    firstName: 'Josefa',       
    lastName: 'Wolff',
    namePrefix: 'Miss',        
    nameSuffix: 'I',
    phonenum: '342-473-6281'   
  },
  {
    street: 'Pattie Street',
    country: 'French Southern Territories',
    city: 'New Eliasside',
    name: 'Miss Domenico Satterfield',
    age: 53,
    buildingNum: '18',
    firstName: 'Nickolas',
    lastName: 'Hudson',
    namePrefix: 'Ms.',
    nameSuffix: 'MD',
    phonenum: '633-852-8832'
  },
  {
    street: 'Rice Isle',
    country: 'Luxembourg',
    city: 'East Clovis',
    name: 'Miss Wilburn Carter',
    age: 72,
    buildingNum: '1064',
    firstName: 'America',
    lastName: 'Dicki',
    namePrefix: 'Ms.',
    nameSuffix: 'II',
    phonenum: '997-792-3902'
  },
  {
    street: 'Dare Squares',
    country: 'Oman',
    city: 'Klingchester',
    name: 'Ms. Asia Trantow',
    age: 26,
    buildingNum: '540',
    firstName: 'Destinee',
    lastName: 'Ankunding',
    namePrefix: 'Miss',
    nameSuffix: 'II',
    phonenum: '741-654-4805'
  },
  {
    street: 'Dicki Knolls',
    country: 'Cape Verde',
    city: 'Dustinview',
    name: 'Dr. Payton Schowalter',
    age: 68,
    buildingNum: '28',
    firstName: 'Clarabelle',
    lastName: 'Ruecker',
    namePrefix: 'Ms.',
    nameSuffix: 'DVM',
    phonenum: '732-024-4247'
  },
  {
    street: 'Rempel Key',
    country: 'Holy See (Vatican City State)',
    city: 'New Rosalinda',
    name: 'Mr. Walton Krajcik',
    age: 70,
    buildingNum: '405',
    firstName: 'Milford',
    lastName: 'Waelchi',
    namePrefix: 'Mrs.',
    nameSuffix: 'II',
    phonenum: '913-779-2139'
  },
  {
    street: 'Adella Curve',
    country: 'China',
    city: 'South Tiana',
    name: 'Miss Kameron Robel',
    age: 59,
    buildingNum: '86',
    firstName: 'Dario',
    lastName: 'Lehner',
    namePrefix: 'Ms.',
    nameSuffix: 'III',
    phonenum: '863-491-2708'
  },
  {
    street: 'Sunny Curve',
    country: 'Lesotho',
    city: 'Alizestad',
    name: 'Mrs. Audie Ebert',
    age: 38,
    buildingNum: '244',
    firstName: 'Kayley',
    lastName: 'Reynolds',
    namePrefix: 'Miss',
    nameSuffix: 'II',
    phonenum: '165-611-1892'
  },
  {
    street: 'Treutel Road',
    country: 'Fiji',
    city: 'Hosealand',
    name: 'Dr. Delaney McClure',
    age: 46,
    buildingNum: '994',
    firstName: 'Deven',
    lastName: 'Baumbach',
    namePrefix: 'Miss',
    nameSuffix: 'III',
    phonenum: '226-049-0012'
  },
  {
    street: 'Kirsten Parks',
    country: 'Belgium',
    city: 'Lake Steve',
    name: 'Mrs. Eugene Fisher',
    age: 42,
    buildingNum: '694',
    firstName: 'Levi',
    lastName: 'Mills',
    namePrefix: 'Mrs.',
    nameSuffix: 'Sr.',
    phonenum: '434-990-3739'
  },
  {
    street: 'Klein Tunnel',
    country: 'Kiribati',
    city: 'Ebbaville',
    name: 'Mr. Reta Kuphal',
    age: 38,
    buildingNum: '716',
    firstName: 'Buster',
    lastName: 'Homenick',
    namePrefix: 'Mrs.',
    nameSuffix: 'IV',
    phonenum: '358-028-6060'
  },
  {
    street: 'Sienna Land',
    country: 'Saint Barthelemy',
    city: 'Earnestineland',
    name: 'Mrs. Eliane Kiehn',
    age: 59,
    buildingNum: '97',
    firstName: 'Carlotta',
    lastName: 'Gislason',
    namePrefix: 'Miss',
    nameSuffix: 'V',
    phonenum: '772-126-1159'
  },
  {
    street: 'Alena Lodge',
    country: 'Colombia',
    city: 'East Cicero',
    name: 'Miss Joshuah Rath',
    age: 71,
    buildingNum: '7238',
    firstName: 'Cecelia',
    lastName: 'Boyle',
    namePrefix: 'Ms.',
    nameSuffix: 'IV',
    phonenum: '358-006-8135'
  },
  {
    street: 'Morissette View',
    country: 'Brunei Darussalam',
    city: 'Norbertofurt',
    name: 'Ms. Felipa Lynch',
    age: 49,
    buildingNum: '530',
    firstName: 'Constantin',
    lastName: 'Hand',
    namePrefix: 'Miss',
    nameSuffix: 'IV',
    phonenum: '177-179-5157'
  },
  {
    street: 'Howe Junctions',
    country: 'Fiji',
    city: 'North Marciahaven',
    name: 'Ms. Rosemary Ziemann',
    age: 25,
    buildingNum: '651',
    firstName: 'Queen',
    lastName: 'Conn',
    namePrefix: 'Mrs.',
    nameSuffix: 'V',
    phonenum: '762-473-9516'
  },
  {
    street: 'Morissette Groves',
    country: 'Montenegro',
    city: 'Carolanneland',
    name: 'Miss Kitty Walter',
    age: 27,
    buildingNum: '17',
    firstName: 'Lucie',
    lastName: 'Mueller',
    namePrefix: 'Ms.',
    nameSuffix: 'V',
    phonenum: '174-462-6417'
  },
  {
    street: 'Leuschke Isle',
    country: 'Argentina',
    city: 'North Hadley',
    name: 'Ms. Lela Kirlin',
    age: 53,
    buildingNum: '229',
    firstName: 'Walton',
    lastName: 'Cummings',
    namePrefix: 'Mr.',
    nameSuffix: 'IV',
    phonenum: '295-050-9275'
  },
  {
    street: 'Tad Mountain',
    country: 'Macao',
    city: 'Carrollport',
    name: 'Ms. Ephraim Nikolaus',
    age: 26,
    buildingNum: '516',
    firstName: 'Easter',
    lastName: 'Marks',
    namePrefix: 'Miss',
    nameSuffix: 'PhD',
    phonenum: '567-836-0318'
  },
  {
    street: 'Stoltenberg Land',
    country: 'Solomon Islands',
    city: 'Andersonville',
    name: 'Dr. Emery Gusikowski',
    age: 19,
    buildingNum: '9716',
    firstName: 'Keanu',
    lastName: 'Ortiz',
    namePrefix: 'Mr.',
    nameSuffix: 'II',
    phonenum: '299-463-3406'
  },
  {
    street: 'Kuhic Junction',
    country: 'Angola',
    city: 'New Kevon',
    name: 'Dr. Bette Olson',
    age: 69,
    buildingNum: '63',
    firstName: 'Alena',
    lastName: 'Fay',
    namePrefix: 'Mrs.',
    nameSuffix: 'IV',
    phonenum: '616-724-9771'
  },
  {
    street: 'Asia Lodge',
    country: 'Senegal',
    city: 'Port Marcella',
    name: 'Mrs. Archibald Prohaska',
    age: 67,
    buildingNum: '2426',
    firstName: 'Ivy',
    lastName: 'Kulas',
    namePrefix: 'Miss',
    nameSuffix: 'IV',
    phonenum: '005-140-3004'
  },
  {
    street: 'Larson Square',
    country: 'Christmas Island',
    city: 'South Sage',
    name: 'Miss Adolphus Rath',
    age: 70,
    buildingNum: '279',
    firstName: 'Priscilla',
    lastName: 'Fritsch',
    namePrefix: 'Ms.',
    nameSuffix: 'MD',
    phonenum: '281-200-6286'
  },
  {
    street: 'Fritsch Square',
    country: 'Portugal',
    city: 'Bashirianland',
    name: 'Mrs. Destany Jaskolski',
    age: 23,
    buildingNum: '350',
    firstName: 'Carlee',
    lastName: 'Schowalter',
    namePrefix: 'Miss',
    nameSuffix: 'IV',
    phonenum: '036-389-6887'
  },
  {
    street: 'Sheila Wells',
    country: 'Tanzania',
    city: 'South Alyceville',
    name: 'Mrs. Reece Hayes',
    age: 31,
    buildingNum: '872',
    firstName: 'Selena',
    lastName: 'Rempel',
    namePrefix: 'Mrs.',
    nameSuffix: 'Jr.',
    phonenum: '245-920-7251'
  },
  {
    street: 'Domenic Keys',
    country: 'Senegal',
    city: 'Maryberg',
    name: 'Ms. Kurtis Marvin',
    age: 28,
    buildingNum: '856',
    firstName: 'Francisco',
    lastName: 'Torp',
    namePrefix: 'Mrs.',
    nameSuffix: 'III',
    phonenum: '112-677-1368'
  },
  {
    street: 'Deshaun Passage',
    country: "Lao People's Democratic Republic",
    city: 'Waltermouth',
    name: 'Mr. Noemie Dietrich',
    age: 46,
    buildingNum: '680',
    firstName: 'Watson',
    lastName: 'Heathcote',
    namePrefix: 'Mrs.',
    nameSuffix: 'III',
    phonenum: '073-948-7313'
  },
  {
    street: 'Corwin Mission',
    country: 'Macao',
    city: 'New Valentine',
    name: 'Mr. Sharon Boehm',
    age: 22,
    buildingNum: '298',
    firstName: 'Brenna',
    lastName: 'Kshlerin',
    namePrefix: 'Mrs.',
    nameSuffix: 'II',
    phonenum: '704-983-3227'
  },
  {
    street: 'Electa Vista',
    country: 'Cook Islands',
    city: 'Kilbackside',
    name: 'Ms. Olen Connelly',
    age: 38,
    buildingNum: '664',
    firstName: 'Pierre',
    lastName: 'Roob',
    namePrefix: 'Miss',
    nameSuffix: 'MD',
    phonenum: '859-141-3263'
  },
  {
    street: 'Ullrich Station',
    country: 'Syrian Arab Republic',
    city: 'South Destineemouth',
    name: 'Mr. Juanita Weber',
    age: 30,
    buildingNum: '0184',
    firstName: 'Ruthie',
    lastName: 'Romaguera',
    namePrefix: 'Mrs.',
    nameSuffix: 'Sr.',
    phonenum: '425-138-8184'
  }
]

  const countries = users.map((value, index) => {
    return value.country
  })

  const ages = users.map((value, index) => {
    return value.age
  })

  const names = users.map((value, index) => {
    return value.name.toUpperCase()
  })

  const filteredAges = users
    .filter((it) => {
        return it.age > 30 && it.age < 50
    })
    .map((user) => {
        return user.name
    })


    const buildingNumers = users.filter((num) => {
          return num.buildingNum > 1000
        }).map((user) => {
          return user.firstName
    }) 
       
  console.log(buildingNumers)